{
 "title": "Crack Monitoring Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Draw-Wire-Sensor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "_comment": "pos crackmon-03",
     "alias": "pos crackmon-03",
     "query": "from(bucket: \"crackmon_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crackmon_sensor_data\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"crackmon-03\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pos\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "_comment": "temp_ext crackmon-03",
     "alias": "temp_ext crackmon-03",
     "query": "from(bucket: \"crackmon_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crackmon_sensor_data\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"crackmon-03\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp_ext\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "_comment": "temp_pcb crackmon-03",
     "alias": "temp_pcb crackmon-03",
     "query": "from(bucket: \"crackmon_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crackmon_sensor_data\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"crackmon-03\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp_pcb\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery %",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "_comment": "battery crackmon-03",
     "alias": "battery crackmon-03",
     "query": "from(bucket: \"crackmon_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crackmon_sensor_data\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"crackmon-03\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Shahe-Sensor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "_comment": "pos crackmon-02",
     "alias": "pos crackmon-02",
     "query": "from(bucket: \"crackmon_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crackmon_sensor_data\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"crackmon-02\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pos\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery %",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "_comment": "battery crackmon-02",
     "alias": "battery crackmon-02",
     "query": "from(bucket: \"crackmon_test\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crackmon_sensor_data\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"crackmon-02\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}