apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    orgId: 1

    jsonData:
      httpMode: POST
      organization: CrackMon
      defaultBucket: crackmon
      version: Flux

    secureJsonData:
      token: ${INFLUXDB_INIT_ADMIN_TOKEN}

    secureJsonFields:
      token: true
      
    basicAuth: false
    basicAuthEnabled: false
